### ISSUE TITLE
cannot build dotnet 2x

### ISSUE THREAD

**Issue by carlin-q-scott** [carlin-q-scott/aws-eb-dotnet-core-deploy#1]
AWS CLI 3 cannot be installed on the dotnet 2x SDK image due to a system library conflict:

> Downloading https://files.pythonhosted.org/packages/84/0e/0df616d87aaa363454dbf342f7f3996bf036c1a4d5dbf64e8f046fd89142/awsebcli-3.19.2.tar.gz (249kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-zrq_btup/awsebcli/setup.py", line 65, in <module>
long_description=open('README.rst').read() + open('CHANGES.rst').read(),
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14564: ordinal not in range(128)

The latest successful build is using a version of the AWS CLI that is deprecated and can no longer deploy to Elastic Beanstalk.

**Comment by carlin-q-scott** [comment]
I tried various fixes involving the ascii encoding, but failed. Perhaps using the latest python 3.8 might fix it, but I tried python 3.7 already and it did not fix the issue. There may also be a better way to install the AWS CLI.
